### ISSUE TITLE
example for configuration from offline sources - wavetable oscillators

### ISSUE THREAD

**Issue by HighHarmonics2** [shakfu/py2max#2]
The README possible use cases includes: 

Create parametrizable objects with configuration from offline sources. For example, one-of-a-kind wavetable oscillators configured from random wavetable files.

This sounds great and I would be interested in doing this, but I can't quite understand how it would work. A small example file for such a use case would be helpful.

**Comment by shakfu** [comment]
Thanks for your interest. I would suggest to look at the Max help file for the `[table~]` object and then look at the `tests/test_add_tilde.py` for an example of pre-populating a `[table~]` object via py2max.

Ideally you would want to use a python library to generate the waveform for you. 

A quick scan reveals the following possibly helpful packages:

- [WaveGenPy](https://github.com/EfiPy/WaveGenPy)
- [PySineWave](https://github.com/daviddavini/pysinewave)
- [chippy](https://github.com/benmoran56/chippy)

or for some heavy lifting try [librosa](https://librosa.org) which is pretty full featured.

Also the following articles may be useful:

- [Generate Audio with Python](https://zach.se/generate-audio-with-python/)
- [Generate Sounds with Python](https://capital-g.github.io/musikinformatik-sose2021/01_spect_resynth/canvas.html)

**Comment by shakfu** [comment]
@HighHarmonics2 I have added a basic test to `tests/test_table.py` to demonstrate the concept. 

A better way would be to generate a `.wav` file via python ([scipy.signal](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.sawtooth.html) is a good example) and then use that in a buffer for a wavetable. (see `[cycle~]` help for example).

**Comment by HighHarmonics2** [comment]
Got it. Thanks for adding the test and giving suggestions on python packages and sources. Appreciated!

**Comment by shakfu** [comment]
@HighHarmonics2 

My pleasure. Incidentally, if you want to look at a real-world (advanced) example of using the library, check out the [faust2rnbo](https://github.com/grame-cncm/faust/blob/master-dev/architecture/max-msp/rnbo.py) feature from the [faust](https://github.com/grame-cncm/faust) platform.
