### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by HighHarmonics2** [shakfu/py2max#3]
I notice that the README indicates that py2max is a library without dependencies. 

I did encounter dependencies when running the tests via pytest. These packages are needed:
networkx
matplotlib
pygraphviz

pygraphviz further requires install of Graphviz (manual or via brew) which itself has extensive package dependencies. 

I don't mind installing pip packages, but my suggestion is to clarify the dependency statement. I realize these installs were only required to run the test capability. 

Perhaps something like: py2max is a library that doesn't require additional packages for basic use. Some additional packages are required for running the tests. 

Also, an install guide section in the README would be helpful: 

- install the repo via git or download
- for running tests, the following additional python packages are required:
-  networkx
- matplotlib
- pygraphviz
- Pygraphviz requires install of the program GraphViz: https://www.graphviz.org/ 
(On macos this can be done via `brew install graphviz`.) This install is fairly involved and will take some time. Once complete, you can use pip install for  pygraphviz

**Comment by shakfu** [comment]
@HighHarmonics2 

Thanks for your feedback and good suggestions.

Incidentally, the intention was to skip a test if an import was not found via the `pytest.mark.skipif` mechanism, but you found some old cases which were not converted. That has been done now in the latest commit.

**Comment by shakfu** [comment]
@HighHarmonics2 Are you still having problems with running tests?

**Comment by HighHarmonics2** [comment]
I can now run tests successfully, thanks. 
As per the README:
`pytest -v` outputs the tests PASSED and tests SKIPPED. This is helpful and with your updated Installation notes, I can understand which packages I don't have installed - it looks like mostly on the layout tests that need pyhola, tsmpy, adaptagrams, etc. This is nice as I can decide if I want this package or not. 

This issue can be closed.
