### ISSUE TITLE
Apply layout option to gen and subpatch

### ISSUE THREAD

**Issue by HighHarmonics2** [shakfu/py2max#7]
I added a layout value to the main patch and would like the layout to extend to subpatches and gen~  patches. 
I tried adding the layout value to the add_gen function. It compiled fine. The main patch layout was veritical, but the gen~ patch was horizontal.

```
p = py2max.Patcher(maxFileName, layout="vertical")
sbox = p.add_gen_tilde(layout="vertical")
```

Is there a way to do this?

**Comment by shakfu** [comment]
Currently, the `layout="vertical"` or `layout="horizontal"` keyword only works on the top-level patcher... I think I fixed this in one of the experimental branches, but until I fix it on the main branch you should note the following:

```python
    def add_gen(self, text: str = None, tilde=False, **kwds):
        """Add a gen object."""
        prefix = "gen~" if tilde else "gen"
        _text = f"{prefix} {text}" if text else prefix
        return self.add_subpatcher(
            _text, patcher=Patcher(parent=self, classnamespace="dsp.gen"), **kwds
        )
```
A keyword won't work, but what will is if you do the following;

```python
In [1]: from py2max import Patcher

In [2]: p = Patcher('test.maxpat', layout='vertical')

In [3]: p._layout_mgr
Out[3]: <py2max.core.VerticalLayoutManager at 0x1013c1c90>

In [4]: sb = p.add_gen_tilde()

In [5]: sb.subpatcher._layout_mgr = sb.subpatcher.set_layout_mgr("horizontal")

In [6]: sb.subpatcher._layout_mgr
Out[6]: <py2max.core.HorizontalLayoutManager at 0x102c701d0>

```

Also note that layout is "horizontal" by default so you don't need to do that last part for the subpatcher in any case:

```python
class Patcher:
    def __init__(
        self,
        ...
        layout: str = "horizontal",
        ...

    ):
```
